import { AppToaster } from "@/components/ui/toast"
import GlobalNavbar from "@/components/GlobalNavbar"
import Footer from "@/components/Footer"

import Script from "next/script"
import GoogleAnalyticsTracker from "@/components/GoogleAnalyticsTracker"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');
          `}
        </Script>
      </head>

      {/* We voegen bg-slate-100 toe aan de body zodat je de 'box' goed ziet */}
      <body className="bg-slate-100 min-h-screen font-sans antialiased">
        <GoogleAnalyticsTracker />

        {/* De Navbar moet ook binnen de begrenzer vallen */}
        <div className="max-w-300 mx-auto bg-white shadow-2xl min-h-screen relative overflow-hidden flex flex-col">
          
          <GlobalNavbar />

          {/* BELANGRIJK: We halen p-20 weg en gebruiken h-full. 
            Dit is de plek waar je 'children' (je spel) leven.
          */}
          <main className="flex-1 relative">
            {children}
          </main>

          {/* De Footer moet binnen de 1200px container blijven */}
          <div className="sticky bottom-0 left-0 right-0 z-50">
            <Footer />
          </div>
        </div>

        <AppToaster />
      </body>
    </html>
  )
}