import { AppToaster } from "@/components/ui/toast"
import GlobalNavbar from "@/components/GlobalNavbar"
import Footer from "@/components/Footer"

import Script from "next/script"
import GoogleAnalyticsTracker from "@/components/GoogleAnalyticsTracker"

import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');
          `}
        </Script>
      </head>

      <body className="bg-[#F0F7FF] min-h-screen">
        {/* Google Analytics page view tracker */}
        <GoogleAnalyticsTracker />

        <GlobalNavbar />

        {/* AANPASSING HIERONDER:
          1. 'max-w-screen-xl' zorgt dat de content stopt bij 1280px breedte.
          2. 'mx-auto' centreert het blok op je scherm.
          3. 'p-6 md:p-10' vervangt de p-20 voor een betere schaling.
        */}
        <div className="max-w-7xl mx-auto p-6 md:p-10 mt-10 mb-24">
          {children}
        </div>

        {/* Zorg dat de footer een hogere z-index heeft zodat hij 
          niet achter andere elementen verdwijnt 
        */}
        <div className="fixed bottom-0 left-0 right-0 z-50">
          <Footer />
        </div>

        <AppToaster />
      </body>
    </html>
  )
}